name: vsm_frigo_prod

services:

  app:
    build:
      dockerfile: Dockerfile.prod
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - static:/app/static
    networks:
      - backnet
    env_file:
      - .env
    user: "${UID}:${GID}"
    restart: unless-stopped
    
  
  nginx_prod:
    container_name: nginx_prod
    image: nginx:latest
    ports:
      - "127.0.0.1:${PORT}:80"
    networks:
      - backnet
    depends_on:
      - app
    volumes:
      - ./proxy/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
    restart: unless-stopped
  
networks:
  backnet:
volumes:
  static: